#!/usr/bin/env node
/**
 * Scenario 3 — Generate amplified mock data for frontend stress tests.
 *
 * Writes large class / answer datasets to src/data/__loadtest__/.
 * The frontend loads these instead of the normal mocks when the env var
 * VITE_USE_LOADTEST_DATA=1 is set at build/dev time.
 *
 * Usage:
 *   node load-tests/frontend_data.mjs [--students N] [--classes M]
 *
 * Defaults: 200 students per class × 1 class. Adjust to stress different axes.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "..");
const OUT_DIR = resolve(PROJECT_ROOT, "src/data/__loadtest__");

// ── Parse args ───────────────────────────────────────────────────────────
const args = Object.fromEntries(
  process.argv
    .slice(2)
    .map((a, i, arr) => (a.startsWith("--") ? [a.slice(2), arr[i + 1]] : null))
    .filter(Boolean),
);
const STUDENTS_PER_CLASS = Number.parseInt(args.students ?? "200", 10);
const CLASS_COUNT = Number.parseInt(args.classes ?? "1", 10);

// ── Fake-data generators ─────────────────────────────────────────────────
const SURNAMES = "陳林黃張李王吳劉蔡楊許鄭謝郭洪邱曾廖賴".split("");
const GIVEN_NAMES = [
  "小明", "美玲", "志豪", "佳慧", "俊傑", "雅婷", "建宏", "淑芬", "宗翰",
  "雨晴", "文彬", "欣妤", "偉誠", "芷瑄", "明哲", "怡君", "柏宇", "佩珊",
  "振源", "雅文", "宜庭", "承翰", "佳蓉", "宗霖", "育誠", "亭妤",
];

const randName = (i) =>
  `${SURNAMES[i % SURNAMES.length]}${GIVEN_NAMES[i % GIVEN_NAMES.length]}${
    i >= GIVEN_NAMES.length ? Math.floor(i / GIVEN_NAMES.length) : ""
  }`;

// All 5 nodes covered by quiz-001 / quiz-002 in CLAUDE.md
const QUIZ_NODES = ["INe-II-3-02", "INe-II-3-03", "INe-II-3-05", "INe-Ⅲ-5-4", "INe-Ⅲ-5-7"];

// 4 misconceptions per node = M02-1..4, M03-1..4, M05-1..4, M11-1..4, M12-1..4
const misconceptionsForNode = (nodeId) => {
  const num = nodeId.startsWith("INe-II-3-") ? nodeId.slice(-2) : `1${nodeId.slice(-1)}`;
  return [1, 2, 3, 4].map((i) => `M${num}-${i}`);
};

// ── Build datasets ───────────────────────────────────────────────────────
const classes = [];
const allStudents = [];

for (let c = 0; c < CLASS_COUNT; c++) {
  const classId = `loadtest-class-${String.fromCharCode(65 + c)}`;
  const students = Array.from({ length: STUDENTS_PER_CLASS }, (_, i) => {
    const seat = i + 1;
    const account = `LT${c}${String(seat).padStart(4, "0")}`;
    const s = {
      id: account,
      account,
      name: randName(i),
      seat,
      classId,
    };
    allStudents.push(s);
    return s;
  });

  classes.push({
    id: classId,
    name: `壓測班 ${String.fromCharCode(65 + c)}（${STUDENTS_PER_CLASS} 人）`,
    grade: "五年級",
    subject: "自然科學",
    color: "#C8EAAE",
    textColor: "#3D5A3E",
    schoolYear: 2025,
    semester: "second",
    status: "active",
    students,
  });
}

// One answer row per (student, node, misconception). For 200 students × 5
// nodes × 4 misconceptions = 4000 rows per class — plenty to stress Recharts.
const answers = [];
let answerId = 1;
for (const s of allStudents) {
  for (const nodeId of QUIZ_NODES) {
    for (const mid of misconceptionsForNode(nodeId)) {
      const isCorrect = Math.random() < 0.55;
      answers.push({
        id: answerId++,
        studentId: s.id,
        classId: s.classId,
        quizId: Math.random() < 0.5 ? "quiz-001" : "quiz-002",
        nodeId,
        misconceptionId: mid,
        correct: isCorrect,
        selectedTag: isCorrect ? "correct" : mid,
        diagnosis: isCorrect ? null : mid,
        answeredAt: new Date(Date.now() - Math.random() * 30 * 86400_000).toISOString(),
      });
    }
  }
}

// ── Emit ES modules under src/data/__loadtest__/ ─────────────────────────
mkdirSync(OUT_DIR, { recursive: true });

const stamp = `// AUTO-GENERATED by load-tests/frontend_data.mjs at ${new Date().toISOString()}\n// DO NOT EDIT — re-run the generator with different flags instead.\n\n`;

writeFileSync(
  resolve(OUT_DIR, "classData.large.js"),
  stamp + `export const loadtestClasses = ${JSON.stringify(classes, null, 2)};\n`,
);
writeFileSync(
  resolve(OUT_DIR, "answers.large.js"),
  stamp + `export const loadtestAnswers = ${JSON.stringify(answers, null, 2)};\n`,
);

const summary = {
  generatedAt: new Date().toISOString(),
  classes: classes.length,
  studentsPerClass: STUDENTS_PER_CLASS,
  totalStudents: allStudents.length,
  totalAnswers: answers.length,
  nodes: QUIZ_NODES,
};
writeFileSync(
  resolve(OUT_DIR, "meta.json"),
  JSON.stringify(summary, null, 2) + "\n",
);

console.log("─── Loadtest dataset generated ────────────");
console.log(`  output dir   : ${OUT_DIR}`);
console.log(`  classes      : ${summary.classes}`);
console.log(`  students     : ${summary.totalStudents}`);
console.log(`  answer rows  : ${summary.totalAnswers}`);
console.log("─────────────────────────────────────────────");
console.log("Next steps:");
console.log("  1. Set VITE_USE_LOADTEST_DATA=1 and run `npm run dev`");
console.log("  2. Open Chrome DevTools Performance — see load-tests/frontend_profiling.md");
